### PR TITLE
Prefix functions in utils with ayatana_common_utils_

### PR DESCRIPTION
**Pull request by tari01**
fixes https://github.com/AyatanaIndicators/libayatana-common/issues/18

### CODE REVIEW

**Review by sunweaver — COMMENTED** [review]
LGTM. However, we should keep the old symbols as DEPRECATED symbols around for a while. Also, we probably should do an SONAME version bump (libayatana-common.so.0 -> libayatana.so.1), don't you think?

@tari01: I will do a merge for this now, which will break these indicators until they have been adapted.

Not approving yet, waiting for your feedback first...

**Comment by tari01** [comment]
> LGTM. However, we should keep the old symbols as DEPRECATED symbols around for a while. Also, we probably should do an SONAME version bump (libayatana-common.so.0 -> libayatana.so.1), don't you think?
> 
> @tari01: I will do a merge for this now, which will break these indicators until they have been adapted.
> 
> Not approving yet, waiting for your feedback first...

I think it is safe to break things now. Nothing we've released so far actually uses libayatana-common. I would even keep the SONAME (this will still be the first release to link against).

**Comment by sunweaver** [comment]
> @tari01: I will do a merge for this now, which will break these indicators until they have been adapted.

Urgh, I won't do a merge, let's rather have the old symbols as DEPRECATED symbols and fix the other indicators on the way without causing FTBFS disturbances.

**Comment by sunweaver** [comment]
> > @tari01: I will do a merge for this now, which will break these indicators until they have been adapted.
> 
> Urgh, I won't do a merge, let's rather have the old symbols as DEPRECATED symbols and fix the other indicators on the way without causing FTBFS disturbances.

Hmmm... ok, then. Merging and breaking things now.

**Pull request merged**
