### PR TITLE
Skip elipsizing if max characters are 0

### PR DESCRIPTION
**Pull request by tari01**
fixes https://github.com/AyatanaIndicators/libayatana-common/issues/29

### CODE REVIEW

**Comment by sunweaver** [comment]
@tari01: Please provide a unit test case with this change. Thanks!

**Review by sunweaver — CHANGES_REQUESTED** [review]
See my comment from last night. Please cover the new if-clause extension by unit tests. Thanks.

**Comment by tari01** [comment]
> See my comment from last night. Please cover the new if-clause extension by unit tests. Thanks.

@sunweaver I think we're done.

**Comment by tari01** [comment]
> See my comment from last night. Please cover the new if-clause extension by unit tests. Thanks.

@sunweaver Done.

**Pull request merged**
